# Generated by Django 3.2.10 on 2022-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0003_auto_20220715_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(default='', max_length=25)),
                ('value', models.CharField(default='', max_length=255)),
                ('descr', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
